'use strict';
/* ISO-3166 alpha-2 → country names (for signup dropdown) */
module.exports = {
  US: 'United States', CA: 'Canada', MX: 'Mexico', BR: 'Brazil', AR: 'Argentina', CL: 'Chile',
  CO: 'Colombia', PE: 'Peru', UY: 'Uruguay', PY: 'Paraguay', BO: 'Bolivia', EC: 'Ecuador',
  VE: 'Venezuela', PA: 'Panama', CR: 'Costa Rica', DO: 'Dominican Republic', GT: 'Guatemala',
  HN: 'Honduras', NI: 'Nicaragua', SV: 'El Salvador', CU: 'Cuba', JM: 'Jamaica', TT: 'Trinidad & Tobago',
  BB: 'Barbados', BS: 'Bahamas', HT: 'Haiti',
  GB: 'United Kingdom', DE: 'Germany', FR: 'France', IT: 'Italy', ES: 'Spain', NL: 'Netherlands',
  BE: 'Belgium', AT: 'Austria', IE: 'Ireland', PT: 'Portugal', GR: 'Greece', FI: 'Finland',
  SK: 'Slovakia', SI: 'Slovenia', LT: 'Lithuania', LV: 'Latvia', EE: 'Estonia', LU: 'Luxembourg',
  CY: 'Cyprus', MT: 'Malta', HR: 'Croatia', BG: 'Bulgaria', RO: 'Romania', CZ: 'Czechia',
  HU: 'Hungary', PL: 'Poland', DK: 'Denmark', SE: 'Sweden', NO: 'Norway', IS: 'Iceland',
  CH: 'Switzerland', TR: 'Turkey', RU: 'Russia', UA: 'Ukraine', RS: 'Serbia', MD: 'Moldova',
  GE: 'Georgia', AM: 'Armenia', AZ: 'Azerbaijan', BY: 'Belarus', AL: 'Albania', MK: 'North Macedonia',
  BA: 'Bosnia & Herzegovina', ME: 'Montenegro',
  NG: 'Nigeria', ZA: 'South Africa', KE: 'Kenya', GH: 'Ghana', EG: 'Egypt', MA: 'Morocco',
  TZ: 'Tanzania', UG: 'Uganda', DZ: 'Algeria', SN: 'Senegal', CI: "Côte d'Ivoire", ML: 'Mali',
  BF: 'Burkina Faso', BJ: 'Benin', TG: 'Togo', NE: 'Niger', GN: 'Guinea', GW: 'Guinea-Bissau',
  LR: 'Liberia', SL: 'Sierra Leone', GM: 'Gambia', CV: 'Cape Verde', CM: 'Cameroon', GA: 'Gabon',
  CG: 'Congo', TD: 'Chad', CF: 'Central African Republic', GQ: 'Equatorial Guinea', LY: 'Libya',
  TN: 'Tunisia', ET: 'Ethiopia', ZM: 'Zambia', ZW: 'Zimbabwe', BW: 'Botswana', NA: 'Namibia',
  MW: 'Malawi', MZ: 'Mozambique', AO: 'Angola', RW: 'Rwanda', BI: 'Burundi', MU: 'Mauritius',
  SC: 'Seychelles', SO: 'Somalia', SS: 'South Sudan', ER: 'Eritrea', DJ: 'Djibouti',
  AE: 'United Arab Emirates', SA: 'Saudi Arabia', QA: 'Qatar', KW: 'Kuwait', BH: 'Bahrain',
  OM: 'Oman', JO: 'Jordan', IL: 'Israel', LB: 'Lebanon', IQ: 'Iraq', YE: 'Yemen', SY: 'Syria',
  IN: 'India', CN: 'China', JP: 'Japan', KR: 'South Korea', TW: 'Taiwan', HK: 'Hong Kong',
  SG: 'Singapore', MY: 'Malaysia', TH: 'Thailand', ID: 'Indonesia', PH: 'Philippines',
  VN: 'Vietnam', PK: 'Pakistan', BD: 'Bangladesh', LK: 'Sri Lanka', NP: 'Nepal', AF: 'Afghanistan',
  KZ: 'Kazakhstan', UZ: 'Uzbekistan', MN: 'Mongolia', MM: 'Myanmar', KH: 'Cambodia', LA: 'Laos',
  BN: 'Brunei', KG: 'Kyrgyzstan', TJ: 'Tajikistan', TM: 'Turkmenistan', BT: 'Bhutan', MV: 'Maldives',
  AU: 'Australia', NZ: 'New Zealand', FJ: 'Fiji', PG: 'Papua New Guinea', WS: 'Samoa',
  TO: 'Tonga', VU: 'Vanuatu', SB: 'Solomon Islands'
};
